// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace avro.bean
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Country : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Country\",\"namespace\":\"avro.bean\",\"fields\":[{\"name\":\"id\"," +
				"\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"currency\",\"type\":\"string\"" +
				"},{\"name\":\"PIB\",\"type\":\"float\"}]}");
		private int _id;
		private string _name;
		private string _currency;
		private float _PIB;
		public virtual Schema Schema
		{
			get
			{
				return Country._SCHEMA;
			}
		}
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public string currency
		{
			get
			{
				return this._currency;
			}
			set
			{
				this._currency = value;
			}
		}
		public float PIB
		{
			get
			{
				return this._PIB;
			}
			set
			{
				this._PIB = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.name;
			case 2: return this.currency;
			case 3: return this.PIB;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int32)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.currency = (System.String)fieldValue; break;
			case 3: this.PIB = (System.Single)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
