// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace avro.bean
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Person : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"avro.bean\",\"fields\":[{\"name\":\"count" +
				"ry_id\",\"type\":\"int\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"ty" +
				"pe\":\"string\"},{\"name\":\"age\",\"type\":\"int\"}]}");
		private int _country_id;
		private string _firstName;
		private string _lastName;
		private int _age;
		public virtual Schema Schema
		{
			get
			{
				return Person._SCHEMA;
			}
		}
		public int country_id
		{
			get
			{
				return this._country_id;
			}
			set
			{
				this._country_id = value;
			}
		}
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		public int age
		{
			get
			{
				return this._age;
			}
			set
			{
				this._age = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.country_id;
			case 1: return this.firstName;
			case 2: return this.lastName;
			case 3: return this.age;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.country_id = (System.Int32)fieldValue; break;
			case 1: this.firstName = (System.String)fieldValue; break;
			case 2: this.lastName = (System.String)fieldValue; break;
			case 3: this.age = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
